name: Release

on:
  push:
    branches:
      - main  # or the branch you want to use

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # adjust to your Node.js version

      - name: Increment version
        id: increment_version
        run: |
          # Define the version pattern and increment logic
          VERSION_FILE="version.txt"
          if [ ! -f "$VERSION_FILE" ]; then
            echo "testing.0.0" > $VERSION_FILE
          fi

          CURRENT_VERSION=$(cat $VERSION_FILE)
          echo "Current version: $CURRENT_VERSION"

          # Extract the numeric part of the version
          VERSION_PARTS=(${CURRENT_VERSION//./ })
          MAJOR=${VERSION_PARTS[1]}
          MINOR=${VERSION_PARTS[2]}

          # Increment the minor version
          NEW_MINOR=$((MINOR + 1))
          NEW_VERSION="testing.0.${NEW_MINOR}"

          echo "New version: $NEW_VERSION"
          echo $NEW_VERSION > $VERSION_FILE

      - name: Commit new version
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add version.txt
          git commit -m "Bump version to $NEW_VERSION"
          git tag -a $NEW_VERSION -m "Release $NEW_VERSION"
          git push origin main --tags

