name: Release

on:
  push:
    branches:
      - main  # or the branch you want to use

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Increment version
        id: increment_version
        run: |
          # Define the file to update
          HTML_FILE="testing.html"
          VERSION_REGEX='s/testing\.\([0-9]\{1,\}\)\.\([0-9]\{1,\}\)/testing\.\1\.\2/g'
          
          # Extract current version from HTML file
          CURRENT_VERSION=$(grep -oP '(?<=testing\.)\d+\.\d+' $HTML_FILE | head -n 1)
          
          if [ -z "$CURRENT_VERSION" ]; then
            CURRENT_VERSION="0.0"
          fi

          echo "Current version: $CURRENT_VERSION"

          # Increment the minor version
          VERSION_PARTS=(${CURRENT_VERSION//./ })
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          NEW_MINOR=$((MINOR + 1))
          NEW_VERSION="testing.${MAJOR}.${NEW_MINOR}"

          echo "New version: $NEW_VERSION"

          # Update the version in the HTML file
          sed -i "s/testing\.[0-9]\+\.[0-9]\+/testing.${MAJOR}.${NEW_MINOR}/g" $HTML_FILE

      - name: Commit changes
        run: |
          git config --local user.name "somugnanasekar"
          git config --local user.email "somugnanasekaran@gmail.com"
          git add index.html
          git commit -m "Update version to $NEW_VERSION"
          git push origin main
